---
title: "Practica 11 Prueba de Hipotesis"
author: "Darlyn Iveth Puentes Jimenez"
date: "2023-10-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)

hogares<- read.csv("hogares_enigh.csv",sep = ",")

```

```{r}
sample(hogares$folioviv,10)# muestra representativa,10 viviendas de manera aleatoria
```
```{r}
library(devtools)
install_github("DFJL/SamplingUtil")
```
```{r}
library(SamplingUtil)
N=nrow(hogares)
sys.sample(N,n=10)
```
## Muestreo Sistematico
```{r}
hogares$folioviv[sys.sample(N,n=10)]
```

```{r}
vivienda=seq(1:100)
sample(vivienda,10)
```


```{r}
sys.sample(100,10)
```


## Muestreo estratificado


```{r}
hombres=subset(hogares,sexo_jefe==1)
sample(hombres$folioviv,5)
mujeress=subset(hogares,sexo_jefe==1)
sample(mujeress$folioviv,5)
```

## Muestreo por conglomerado

## Distribucion muestral
```{r}
library(dplyr)
library(tidyverse)

n=10
r=10000
muestras=matrix(rexp(n*r,3),r)
muestras.df=data.frame(t(muestras))
media=data.frame(X1=apply(muestras.df,2,mean))
med_pob=mean(media$X1)

label.left=paste0("Media de 1 \n muestra: ",round(media$X1[1],3))

grafica1 <- muestras.df %>% ggplot() +
geom_histogram(aes(x=X1),bins=10) +
annotate("text", x=0.6 , y=2.75 , label=label.left)
grafica1


```
## Grafico de los promedios 
```{r}
label.right <- paste0("Media de las \n distribución \n muestral \n con ", r," muestras \n de tamaño \n ", n," cada una:", round(med_pob,3))
grafica2 <- media %>%
ggplot() +
geom_histogram(aes(x=X1), col="red") +
annotate("text",x=0.7, y=900, label=label.right)
grafica2

```

```{r}
cowplot::plot_grid(grafica1,grafica2)
```


```{r}
n = 200 # Número de observaciones en cada muestra
r=10000 # Número de replicas / número de muestras a recolectar
muestras <- matrix(rexp(n*r,3),r)
muestras.df <- data.frame(t(muestras))
media <- data.frame(X1=apply(muestras.df,2,mean))
media_poblacional <- mean(media$X1)
label.left <- paste0("Media de 1 \n muestra: ",round(media$X1[1],3))
grafica1 <- muestras.df %>%
ggplot() +
geom_histogram(aes(x=X1),bins=10) +
annotate("text", x=1.2 , y=40 , label=label.left)
label.right <- paste0("Media de las \n distribución \n muestral \n con ", r," muestras \n de tamaño \n ", n," cada una:", round(media_poblacional,3))
grafica2 <- media %>%
ggplot() +
geom_histogram(aes(x=X1)) +
scale_x_continuous(limits = c(0.2,0.6)) + xlab("medias") +
annotate("text",x=0.5, y=1500, label=label.right)
cowplot::plot_grid(grafica1,grafica2)



#VAN VALOR ACTUAL NETO Y TASA INTERNA DE RETORNO  TIR 
```

